### PR TITLE
Added noRecompute option to import reducer

### PR DESCRIPTION
**Pull request by tannerlinsley**
This option allows state to be imported without recomputing each action along the way.

### CODE REVIEW

**Comment by zalmoxisus** [comment]
Thanks for the contribution!

I'm wondering whether we need recomputing here at all. If I'm not missing anything, the only case when it could be necessary is for states without `computedStates` specified. So, it could be:

```js
if(computedStates){
   minInvalidatedStateIndex = Inifinity;
}
```

So, we can skip `computedStates` from the exported object as @calesce suggested [here](https://github.com/gaearon/redux-devtools-log-monitor/pull/46#issuecomment-205008290).

Are other cases when recomputing is necessary here?

cc @gaearon @pabloalonsos

**Comment by zalmoxisus** [comment]
Well, probably when we changed our reducers and import some old state we want the new values there, so just having it configurable makes sense.

**Comment by tannerlinsley** [comment]
You do want it on by default. If you have changed any code that got your
state to that point in time, you may have inadvertently broken something.
By re computing all of the state's, you are running the reducer code for
each action, thereby testing that nothing has changed in those previous
reducers that would cause an error or undesired state

**Comment by zalmoxisus** [comment]
@tannerlinsley, thanks. Could you please update the test to show that the state was really imported without replaying the actions? It could another reducer for `importMonitoredStore`, which should give different result for `INCREMENT` action.

**Comment by tannerlinsley** [comment]
Not sure why tests not passing.  Everything is passing locally, and the eslint errors aren't there.

**Comment by zalmoxisus** [comment]
@tannerlinsley, sorry for misunderstanding. I didn't mean that the tests aren't passing, but that they are not reflecting the current change - don't show whether actions was replaying during the import or not. So, this test doesn't help to avoid breaking that functionality in the future changes, which it should be intended for.

A solution could be to spy whether the reducer is called. Or to have another reducer, which would generate different result in case it is invoked, but as importing doesn't replay actions, the result would still be the same as the exported value.

**Comment by tannerlinsley** [comment]
I see what you mean.  I thought that showing `computedStates === undefined` when passing in
```
stagedActions: [..,..,..],
computedStates: null
```
would prove that the actions are in fact not getting run.  If they were being run, `computedStates` would not be `null`

If this isn't clear enough, I can rewrite the tests as you outlined above.

**Comment by zalmoxisus** [comment]
It does the trick indeed. I just didn't get what is happening there. Thanks a lot for the contribution!

**Comment by tannerlinsley** [comment]
Awesome! Thanks!

**Comment by tannerlinsley** [comment]
This is great!  It's perfect for importing on states that already have values.  That way, the imported state doesn't base it's actions on the previous computed state.  (imagine a counter that normally counts up every time you import a state, sometimes the desired result its to make the count be a specific number post-import)  @zalmoxisus could we do a patch release?

**Comment by zalmoxisus** [comment]
@tannerlinsley 👍 
It's up in `1.1.0`.

**Pull request merged**
